// GENERATED by bin/derive from distilled/fields.yaml — do not edit.
// Source: draft-ietf-vcon-vcon-core-04 -04
// Types only; per-type applicability rules are not expressed here.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VCon {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vcon: Option<String>,  // §4.1.1 MUST
    pub uuid: String,  // §4.1.2 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Vec<String>>,  // §4.1.3 SHOULD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub critical: Option<Vec<String>>,  // §4.1.4 MUST
    pub created_at: String,  // §4.1.5 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,  // §4.1.6 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,  // §4.1.7 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redacted: Option<serde_json::Value>,  // §4.1.8 / §4.1.8.1 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amended: Option<serde_json::Value>,  // §4.1.9 / §4.1.9.1 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parties: Option<Vec<serde_json::Value>>,  // §4.1.10 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dialog: Option<Vec<serde_json::Value>>,  // §4.1.11 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub analysis: Option<Vec<serde_json::Value>>,  // §4.1.12 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<serde_json::Value>>,  // §4.1.13 none
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Party {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tel: Option<String>,  // §4.2.1 SHOULD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sip: Option<String>,  // §4.2.2 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stir: Option<String>,  // §4.2.3 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mailto: Option<String>,  // §4.2.4 MAY
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,  // §4.2.5 SHOULD
    pub did: String,  // §4.2.6 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation: Option<String>,  // §4.2.7 SHOULD NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gmlpos: Option<String>,  // §4.2.8 none
    pub civicaddress: serde_json::Value,  // §4.2.9 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,  // §4.2.10 MAY
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type: Option<String>,  // §4.2.11 SHOULD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub org: Option<String>,  // §4.2.12 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dept: Option<String>,  // §4.2.13 none
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Dialog {
    pub type: String,  // §4.3.1 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,  // §4.3.2 SHOULD
    pub duration: serde_json::Value,  // §4.3.3 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parties: Option<serde_json::Value>,  // §4.3.4 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub originator: Option<serde_json::Value>,  // §4.3.5 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recordings: Option<serde_json::Value>,  // §4.3.6 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recording_set: Option<serde_json::Value>,  // §4.3.7 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mediatype: Option<serde_json::Value>,  // §4.3.8 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,  // §4.3.9 MUST NOT
    pub disposition: String,  // §4.3.11 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<serde_json::Value>,  // §4.3.12 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application: Option<serde_json::Value>,  // §4.3.15 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,  // §4.3.16 MUST NOT
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_history_objects_array: Option<serde_json::Value>,  // §4.3.13 MUST NOT
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Attachment {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub purpose: Option<String>,  // §4.4.1 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,  // §4.4.2 none
    pub party: serde_json::Value,  // §4.4.3 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dialog: Option<serde_json::Value>,  // §4.4.4 none
    pub mediatype: serde_json::Value,  // §4.4.5 MUST
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,  // §4.4.6 none
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Analysis {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub type: Option<String>,  // §4.5.1 SHOULD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dialog: Option<serde_json::Value>,  // §4.5.2 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment: Option<serde_json::Value>,  // §4.5.3 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mediatype: Option<serde_json::Value>,  // §4.5.4 SHOULD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,  // §4.5.5 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,  // §4.5.6 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product: Option<String>,  // §4.5.7 none
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,  // §4.5.8 none
}
