"""GENERATED by bin/derive from distilled/fields.yaml — do not edit.
Source: draft-ietf-vcon-vcon-core-04 -04

Types only. Two things these types deliberately do NOT express:
  - per-type applicability (vCon §4.3.1.6): a field being present is not
    sufficient, it must be valid FOR THE type value.
  - a MUST on a field VALUE is not a MUST on its PRESENCE. `vcon` carries
    a MUST constraining its value yet is optional; the generator cannot
    tell those apart, so required-ness comes from the field table.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any

@dataclass
class VCon:
    uuid: str  # §4.1.2 MUST
    created_at: str  # §4.1.5 MUST
    vcon: str | None = None  # §4.1.1 MUST
    extensions: list[str] | None = None  # §4.1.3 SHOULD
    critical: list[str] | None = None  # §4.1.4 MUST
    updated_at: str | None = None  # §4.1.6 MUST
    subject: str | None = None  # §4.1.7 none
    redacted: dict | None = None  # §4.1.8 / §4.1.8.1 MUST
    amended: dict | None = None  # §4.1.9 / §4.1.9.1 MUST
    parties: list[dict] | None = None  # §4.1.10 none
    dialog: list[dict] | None = None  # §4.1.11 none
    analysis: list[dict] | None = None  # §4.1.12 none
    attachments: list[dict] | None = None  # §4.1.13 none

@dataclass
class Party:
    did: str  # §4.2.6 MUST
    civicaddress: Any  # §4.2.9 MUST
    tel: str | None = None  # §4.2.1 SHOULD
    sip: str | None = None  # §4.2.2 none
    stir: str | None = None  # §4.2.3 none
    mailto: str | None = None  # §4.2.4 MAY
    name: str | None = None  # §4.2.5 SHOULD
    validation: str | None = None  # §4.2.7 SHOULD NOT
    gmlpos: str | None = None  # §4.2.8 none
    uuid: str | None = None  # §4.2.10 MAY
    type: str | None = None  # §4.2.11 SHOULD
    org: str | None = None  # §4.2.12 none
    dept: str | None = None  # §4.2.13 none

@dataclass
class Dialog:
    type: str  # §4.3.1 MUST
    duration: Any  # §4.3.3 MUST
    disposition: str  # §4.3.11 MUST
    start: str | None = None  # §4.3.2 SHOULD
    parties: Any | None = None  # §4.3.4 MUST NOT
    originator: Any | None = None  # §4.3.5 MUST NOT
    recordings: Any | None = None  # §4.3.6 MUST NOT
    recording_set: Any | None = None  # §4.3.7 MUST NOT
    mediatype: Any | None = None  # §4.3.8 MUST NOT
    filename: str | None = None  # §4.3.9 MUST NOT
    session_id: Any | None = None  # §4.3.12 MUST NOT
    application: object | None = None  # §4.3.15 none
    message_id: str | None = None  # §4.3.16 MUST NOT
    party_history_objects_array: object | None = None  # §4.3.13 MUST NOT

@dataclass
class Attachment:
    party: Any  # §4.4.3 MUST
    mediatype: Any  # §4.4.5 MUST
    purpose: str | None = None  # §4.4.1 none
    start: str | None = None  # §4.4.2 none
    dialog: Any | None = None  # §4.4.4 none
    filename: str | None = None  # §4.4.6 none

@dataclass
class Analysis:
    type: str | None = None  # §4.5.1 SHOULD
    dialog: Any | None = None  # §4.5.2 none
    attachment: Any | None = None  # §4.5.3 none
    mediatype: Any | None = None  # §4.5.4 SHOULD
    filename: str | None = None  # §4.5.5 none
    vendor: str | None = None  # §4.5.6 none
    product: str | None = None  # §4.5.7 none
    schema: str | None = None  # §4.5.8 none
